services:
  web:
    build: .
    container_name: auth_service
    command: gunicorn auth_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app  # Set the working directory inside the container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auth_service_db
    env_file:
      - .env
    restart: always  # Ensures the container restarts if it fails

  db:
    image: postgres:13-alpine 
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s
    restart: always  # Ensures DB container restarts on failure
